In [1]:
my_list=[1,2,3]

In [3]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(5,5)

array([[0.78459277, 0.52161687, 0.50270753, 0.78254728, 0.72507614],
       [0.19047924, 0.52917451, 0.90378423, 0.0584668 , 0.33187954],
       [0.8334731 , 0.85741996, 0.99246769, 0.1271106 , 0.87865854],
       [0.27914701, 0.56570437, 0.30940706, 0.76861871, 0.31225126],
       [0.5799256 , 0.16142084, 0.29283997, 0.44999607, 0.90496976]])

In [29]:
np.random.randn(4,4)

array([[ 1.17846683,  0.17841203, -0.64636311,  0.85995853],
       [ 0.66288602,  1.15092821, -2.52599483,  0.19792452],
       [ 1.15789632,  0.83513765,  0.3239124 , -0.83980509],
       [-0.97124896, -0.15926943,  1.39701552,  1.10588282]])

In [31]:
np.random.randint(1,100,10)

array([35,  2, 96, 61, 65, 47, 73, 88, 55, 80])

In [32]:
arr=np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr=np.random.randint(0,50,10)

In [35]:
ranarr

array([46, 15, 19, 33,  9, 13,  2, 19, 23, 29])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr.max()

46

In [40]:
ranarr.min()

2

In [41]:
ranarr.argmax()

0

In [42]:
ranarr.argmin()

6

In [44]:
arr=arr.reshape(5,5)

In [45]:
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int32')

In [47]:
arr=np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8]

8

In [50]:
arr[1:5]

array([1, 2, 3, 4])

In [51]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [52]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [54]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr[0:5]=100

In [56]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr=np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
slice_of_arr=arr[0:6]

In [60]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [61]:
slice_of_arr[:]=99

In [62]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [63]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy=arr.copy()

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy[:]=100

In [68]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [71]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
arr_2d[0,1]

10

In [75]:
arr_2d[0][0]

5

In [76]:
arr_2d[2,1]

40

In [79]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [80]:
arr=np.arange(1,11)

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
bool_arr=arr>5

In [84]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [85]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [86]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
arr[arr<3]

array([1, 2])

In [88]:
arr_2d=np.arange(50).reshape(5,10)

In [89]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [91]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [92]:
arr=np.arange(0,11)

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [95]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [97]:
arr+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [98]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [100]:
arr-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [101]:
arr / arr

C:\Users\SANCHI~1\AppData\Local\Temp/ipykernel_7280/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [102]:
1/arr

C:\Users\SANCHI~1\AppData\Local\Temp/ipykernel_7280/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [103]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [105]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [107]:
np.max(arr)

10

In [108]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [109]:
np.log(arr)

C:\Users\SANCHI~1\AppData\Local\Temp/ipykernel_7280/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [110]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [112]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [113]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [114]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [115]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.random.rand(1)

array([0.40488104])

In [124]:
np.random.randn(25)

array([-2.68171134, -1.07777363, -1.11667352, -0.94608153,  0.74062145,
        1.15335155,  1.30143918,  0.65776716,  1.72567812, -0.02481135,
       -0.83699201, -0.53930442, -1.24625524,  0.60978102,  0.25977893,
        1.36048488,  2.48241798, -0.26025954, -0.8454638 ,  1.04197821,
        0.9496104 , -2.80396512,  0.07568882,  0.56766517,  0.17015471])

In [128]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [129]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [130]:
mat=np.arange(1,26).reshape(5,5)

In [131]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [132]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [133]:
mat[3,4]

20

In [135]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [136]:
mat[4]

array([21, 22, 23, 24, 25])

In [137]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [138]:
np.sum(mat)

325

In [139]:
np.std(mat)

7.211102550927978

In [147]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])